### ISSUE TITLE
WCS 1.0.0 compliance test result log has an invalid char which is causing a java problem

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs10#54]
If you run the service with te2, wcs 1.0.0 compliance test, you will find the result is not viewable as there is a problem as viewsessionlog.jsp page.

sample service:
http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?request=GetCapabilities&service=WCS&version=1.0.0

let me know if service is inaccessible.
![image](https://user-images.githubusercontent.com/11200872/108766996-aeefb580-750a-11eb-8f84-16436904e7f0.png)

**Comment by keshav-nangare** [comment]
@greatzzk 

The service is inaccessible.

**Comment by keshav-nangare** [comment]
The following tests are getting failed, as they expect exception report as response and currently returning image:
1. wcs1-0-0:getcoverage_operations-getcoverage_request-crs-get-kvp-1
    https://github.com/opengeospatial/ets-wcs10/blob/2af8220d34a38a2d7c090425897b53f203793fe1/src/main/scripts/ctl/wcs.xml#L3982-L3989
```
Request:
    Method: Get
    URL: http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?&WiDtH=200&BbOx=-16704881.0872000009,1108912.52541457303,-11124991.6111871637,9624853.57110000029&CoVeRaGe=mynetcdf&VeRsIoN=1.0.0&HeIgHt=100&FoRmAt=GeoTIFF&SeRvIcE=WCS&ReQuEsT=GetCoverage
```
2. wcs1-0-0:getcoverage_operations-getcoverage_request-crs-get-kvp-3
    https://github.com/opengeospatial/ets-wcs10/blob/2af8220d34a38a2d7c090425897b53f203793fe1/src/main/scripts/ctl/wcs.xml#L4063-L4070
```
Request:
    Method: Get
    URL: http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?&HeIgHt=100&WiDtH=200&SeRvIcE=WCS&CoVeRaGe=mynetcdf&FoRmAt=GeoTIFF&BbOx=-16704881.0872000009,1108912.52541457303,-11124991.6111871637,9624853.57110000029&VeRsIoN=1.0.0&ReQuEsT=GetCoverage&CrS=WCS_CRS_NOT_IN_REQUEST_OR_REQUESTRESPONSE_CRS
```
3. wcs1-0-0:getcoverage_operations-getcoverage_request-crs-post-kvp-1
    https://github.com/opengeospatial/ets-wcs10/blob/2af8220d34a38a2d7c090425897b53f203793fe1/src/main/scripts/ctl/wcs.xml#L4145-L4152
```
Request:
    Method: Post
    URL: http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?
    Body: BbOx=-16704881.0872000009,1108912.52541457303,-11124991.6111871637,9624853.57110000029&VeRsIoN=1.0.0&FoRmAt=GeoTIFF&WiDtH=200&ReQuEsT=GetCoverage&SeRvIcE=WCS&HeIgHt=100&CoVeRaGe=mynetcdf
```
4. wcs1-0-0:getcoverage_operations-getcoverage_request-crs-post-kvp-3
    https://github.com/opengeospatial/ets-wcs10/blob/2af8220d34a38a2d7c090425897b53f203793fe1/src/main/scripts/ctl/wcs.xml#L4226-L4233
```
Request:
    Method: Post
    URL: http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?
    Body: ReQuEsT=GetCoverage&HeIgHt=100&SeRvIcE=WCS&BbOx=-16704881.0872000009,1108912.52541457303,-11124991.6111871637,9624853.57110000029&CoVeRaGe=mynetcdf&FoRmAt=GeoTIFF&WiDtH=200&VeRsIoN=1.0.0&CrS=WCS_CRS_NOT_IN_REQUEST_OR_REQUESTRESPONSE_CRS
```
5. wcs1-0-0:getcoverage_operations-getcoverage_request-response_crs-get-kvp-3
    https://github.com/opengeospatial/ets-wcs10/blob/2af8220d34a38a2d7c090425897b53f203793fe1/src/main/scripts/ctl/wcs.xml#L6811-L6818
```
Request: 
    Method: Get
    URL: http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?&ReSpOnSe_cRs=WCS_COVERAGE_RESPONSE_CRS_INVALID&CrS=EPSG:3857&VeRsIoN=1.0.0&FoRmAt=GeoTIFF&BbOx=-16704881.0872000009,1108912.52541457303,-11124991.6111871637,9624853.57110000029&HeIgHt=100&WiDtH=200&SeRvIcE=WCS&CoVeRaGe=mynetcdf&ReQuEsT=GetCoverage
```
6. wcs1-0-0:getcoverage_operations-getcoverage_request-response_crs-post-kvp-3
    https://github.com/opengeospatial/ets-wcs10/blob/2af8220d34a38a2d7c090425897b53f203793fe1/src/main/scripts/ctl/wcs.xml#L7023-L7030
```
Request:
    Method: Post
    URL: http://54.160.203.226:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer?
    Body: HeIgHt=100&ReQuEsT=GetCoverage&WiDtH=200&VeRsIoN=1.0.0&SeRvIcE=WCS&BbOx=-16704881.0872000009,1108912.52541457303,-11124991.6111871637,9624853.57110000029&FoRmAt=GeoTIFF&CrS=EPSG:3857&CoVeRaGe=mynetcdf&ReSpOnSe_cRs=WCS_COVERAGE_RESPONSE_CRS_INVALID
```


@ghobona @dstenger @greatzzk

Can you please check and give your inputs?
